version: "3.3"

services:
  pc-api:
    container_name: pc-api
    build:
      context: .
    ports:
      - "3000:3000"
    command: [ 'npm', 'run', 'dev' ]
    volumes:
      - .:/pc-api
    depends_on:
      - mongo
  
  mongo:
    container_name: pc-mongo
    image: mongo
    ports:
      - "27000:27017"